export const Jobs = [
  // FIRST CLASSES
  { name: "JT_SWORDMAN", value: "1" },
  { name: "JT_MAGICIAN", value: "2" },
  { name: "JT_ARCHER", value: "3" },
  { name: "JT_ACOLYTE", value: "4" },
  { name: "JT_MERCHANT", value: "5" },
  { name: "JT_THIEF", value: "6" },
  { name: "JT_KNIGHT", value: "7" },
  { name: "JT_PRIEST", value: "8" },
  { name: "JT_WIZARD", value: "9" },
  { name: "JT_BLACKSMITH", value: "10" },
  { name: "JT_HUNTER", value: "11" },
  { name: "JT_ASSASSIN", value: "12" },
  { name: "JT_CRUSADER", value: "14" },
  { name: "JT_MONK", value: "15" },
  { name: "JT_SAGE", value: "16" },
  { name: "JT_ROGUE", value: "17" },
  { name: "JT_ALCHEMIST", value: "18" },
  { name: "JT_BARD", value: "19" },
  { name: "JT_DANCER", value: "20" },

  { name: "JT_SANTA", value: "26" },
  { name: "JT_SUMMER", value: "27" },

  // ADVANCED CLASSES
  { name: "JT_KNIGHT_H", value: "4008" },
  { name: "JT_PRIEST_H", value: "4009" },
  { name: "JT_WIZARD_H", value: "4010" },
  { name: "JT_BLACKSMITH_H", value: "4011" },
  { name: "JT_HUNTER_H", value: "4012" },
  { name: "JT_ASSASSIN_H", value: "4013" },
  { name: "JT_CRUSADER_H", value: "4015" },
  { name: "JT_MONK_H", value: "4016" },
  { name: "JT_SAGE_H", value: "4017" },
  { name: "JT_ROGUE_H", value: "4018" },
  { name: "JT_ALCHEMIST_H", value: "4019" },
  { name: "JT_BARD_H", value: "4020" },
  { name: "JT_DANCER_H", value: "4021" },

  // New
  { name: "JT_RUNE_KNIGHT", value: "4054" },
  { name: "JT_WARLOCK", value: "4055" },
  { name: "JT_RANGER", value: "4056" },
  { name: "JT_ARCHBISHOP", value: "4057" },
  { name: "JT_MECHANIC", value: "4058" },
  { name: "JT_GUILLOTINE_CROSS", value: "4059" },
  { name: "JT_RUNE_KNIGHT_H", value: "4060" },
  { name: "JT_WARLOCK_H", value: "4061" },
  { name: "JT_RANGER_H", value: "4062" },
  { name: "JT_ARCHBISHOP_H", value: "4063" },
  { name: "JT_MECHANIC_H", value: "4064" },
  { name: "JT_GUILLOTINE_CROSS_H", value: "4065" },
  { name: "JT_ROYAL_GUARD", value: "4066" },
  { name: "JT_SORCERER", value: "4067" },
  { name: "JT_MINSTREL", value: "4068" },
  { name: "JT_WANDERER", value: "4069" },
  { name: "JT_SURA", value: "4070" },
  { name: "JT_GENETIC", value: "4071" },
  { name: "JT_SHADOW_CHASER", value: "4072" },
  { name: "JT_KAGEROU", value: "4211" },
  { name: "JT_REBELLION", value: "4215" },
  { name: "JT_DO_SUMMONER", value: "4218" },
  { name: "JT_STAR_EMPEROR", value: "4239" },
  { name: "JT_SOUL_REAPER", value: "4240" },
  { name: "JT_STAR2_EMPEROR", value: "4243" },

  { name: "JT_DRAGON_KNIGHT", value: "4252" },
  { name: "JT_MEISTER", value: "4253" },
  { name: "JT_SHADOW_CROSS", value: "4254" },
  { name: "JT_ARCH_MAGE", value: "4255" },
  { name: "JT_CARDINAL", value: "4256" },
  { name: "JT_WINDHAWK", value: "4257" },
  { name: "JT_IMPERIAL_GUARD", value: "4258" },
  { name: "JT_BIOLO", value: "4259" },
  { name: "JT_ABYSS_CHASER", value: "4260" },
  { name: "JT_ELEMENTAL_MASTER", value: "4261" },
  { name: "JT_INQUISITOR", value: "4262" },
  { name: "JT_TROUBADOUR", value: "4263" },
  { name: "JT_TROUVERE", value: "4264" },

  { name: "JT_SKY_EMPEROR", value: "4302" },
  { name: "JT_SOUL_ASCETIC", value: "4303" },
  { name: "JT_SHINKIRO", value: "4304" },
  { name: "JT_SHIRANUI", value: "4305" },
  { name: "JT_NIGHT_WATCH", value: "4306" },
  { name: "JT_HYPER_NOVICE", value: "4307" },
  { name: "JT_SPIRIT_HANDLER", value: "4308" },
];
